/**
 * Assemble `client.js` from `src/`.
 *
 * The browser module graph loads exactly one bundle per package (`dsh.client` has
 * a single `./client` export; `orderByModuleGraph` forbids a row from depending on
 * itself), so the shipped plugin has to be one self-contained file. The sources
 * stay separate and readable, each one wrapped by this script into a tiny
 * CommonJS-ish registry that the generated factory evaluates in order.
 *
 * The loader contract, verified against a published plugin's own `./client`
 * artifact (`window.__ModuleLoader__.load({ id, factory: (require) => … })`):
 *
 *  - the factory receives the loader's `require` as its FIRST argument, and
 *    that is the only route to platform modules such as `react`;
 *  - the factory's return value is the package's `./client` module;
 *  - the boot manifest loads every declared client module inside an initial
 *    batch, so an uncaught throw here blanks the page rather than the plugin.
 *
 *   node build.mjs        (write client.js)
 *   node build.mjs --check (report drift without writing)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE = "dsh-typewriter-blip";

/** Load order; every entry declares its dependencies by module id. */
const MODULES = [
  { file: "src/settings.js", dir: "settings", deps: ["voices"] },
  { file: "src/voices.js", dir: "voices", deps: [] },
  { file: "src/audio.js", dir: "audio", deps: ["voices"] },
  { file: "src/observer.js", dir: "observer", deps: [] },
  { file: "src/client.js", dir: "client", deps: ["settings", "voices", "audio", "observer"] }
];

/** Dependencies are injected as parameters, so no source file ever calls require() for them. */
const PARAM_NAMES = ["settings", "voices", "audio", "observer"];

/** The load marker test.mjs greps for; kept byte-stable on purpose. */
const LOAD_LINE = `    return registry.load("client");`;

function loadSource(relativePath) {
  return readFileSync(join(HERE, relativePath), "utf8").replace(/\r\n/g, "\n").trimEnd();
}

function assemble() {
  const parts = [];
  parts.push(`/**
 * GENERATED FILE — edit src/*.js and run \`node build.mjs\`.
 *
 * One bundle because the browser module graph loads a single \`./client\` artifact
 * per package. Inside the factory the sources are evaluated in dependency order
 * against a tiny CommonJS-ish registry, so they keep normal module semantics.
 */
window.__ModuleLoader__.load({
  id: "${PACKAGE}",
  factory(loaderRequire) {
`);

  parts.push(assembleRegistry());
  parts.push("");

  for (const [index, entry] of MODULES.entries()) {
    const source = loadSource(entry.file)
      .split("\n")
      .map((line) => (line.length === 0 ? "" : `        ${line}`))
      .join("\n");
    const params = PARAM_NAMES.filter((name) => entry.deps.includes(name));
    parts.push(`    //#region ${entry.file}`);
    parts.push(
      `    registry.define(${JSON.stringify(entry.dir)}, [${entry.deps.map((dep) => JSON.stringify(dep)).join(", ")}], function (module, exports, require${params.length > 0 ? `, ${params.join(", ")}` : ""}) {`
    );
    parts.push(source);
    parts.push("    });");
    parts.push(`    //#endregion ${entry.file}`);
    if (index < MODULES.length - 1) parts.push("");
  }

  parts.push(`
    try {
${LOAD_LINE}
    } catch (error) {
      /* Every declared client module sits in an initial boot batch, so letting
         this escape would blank the whole page over a cosmetic audio plugin.
         Stay a plugin failure: no panel, and the reason on the console. */
      if (typeof console !== "undefined" && typeof console.error === "function") {
        console.error("[typewriter-blip] client module failed to load; the panel stays hidden", error);
      }
      return { name: "typewriter-blip", apply() {} };
    }
  }
});
`);
  return parts.join("\n");
}

function assembleRegistry() {
  const parts = [];
  parts.push(`    /* Generated by build.mjs; see src/. Modules evaluate in dependency order. */`);
  parts.push(`    const factories = new Map();`);
  parts.push(`    const cache = new Map();`);
  parts.push(`    /* Platform modules (react, …) resolve through the loader's own require, which`);
  parts.push(`       arrives as this factory's first argument. Nothing else can supply them. */`);
  parts.push(`    const request = (specifier) => {`);
  parts.push(`      if (typeof loaderRequire === "function") return loaderRequire(specifier);`);
  parts.push(`      const testSeam = globalThis.__DSH_TWB_REQUIRE__;`);
  parts.push(`      if (typeof testSeam === "function") return testSeam(specifier);`);
  parts.push(`      throw new Error("typewriter-blip: no loader for module " + specifier);`);
  parts.push(`    };`);
  parts.push(`    const registry = {`);
  parts.push(`      define(id, dependencies, factory) {`);
  parts.push(`        factories.set(id, { dependencies, factory });`);
  parts.push(`      },`);
  parts.push(`      load(id) {`);
  parts.push(`        if (cache.has(id)) return cache.get(id);`);
  parts.push(`        const entry = factories.get(id);`);
  parts.push(`        if (entry === undefined) throw new Error("typewriter-blip: nothing defines module " + id);`);
  parts.push(`        const module = { exports: {} };`);
  parts.push(`        const dependencies = entry.dependencies.map((dependency) => registry.load(dependency));`);
  parts.push(`        entry.factory(module, module.exports, request, ...dependencies);`);
  parts.push(`        cache.set(id, module.exports);`);
  parts.push(`        return module.exports;`);
  parts.push(`      }`);
  parts.push(`    };`);
  return parts.join("\n");
}

const target = join(HERE, "client.js");

/** Imported by test.mjs, which compares the artifact against this output. */
export { assemble, target, LOAD_LINE };

/** Only the direct CLI invocation writes (or reports drift on) the artifact. */
const invokedDirectly = process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const expected = assemble();
  if (process.argv.includes("--check")) {
    const current = existsSync(target) ? readFileSync(target, "utf8").replace(/\r\n/g, "\n") : "";
    if (current !== expected) {
      console.error("build: client.js is stale; run `node build.mjs`");
      process.exitCode = 1;
    } else {
      console.log("build: client.js is up to date");
    }
  } else {
    mkdirSync(HERE, { recursive: true });
    writeFileSync(target, expected, "utf8");
    console.log(`build: wrote client.js (${expected.length} bytes)`);
  }
}
